Social-Network-master/network/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('n/logout/', views.logout_view, name='logout'),
    path('n/register/', views.register, name='register'),
    path('n/profiles/', views.profile_view, name='profile_view'),
    path('login/', views.login_view, name='login'),
    path('goto-admin/', views.goto_admin, name='goto_admin'),
    path('', views.indexx, name='indexx'),
    
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/', views.user_profile_ajax, name='full_profile'),
    path('ajax/profile/<str:username>/', views.user_profile_ajax, name='user_profile_ajax'),
    path('profile/<str:username>/', views.profile, name='profile'),
    
    path('full_profile/<str:username>/', views.full_profile, name='full_profile'),
    path('ajax/blog_content/', views.load_blog_content, name='blog_content'),
    path('profile/load/<str:username>/', views.load_profile, name='profile_load'),
    path('users/', views.users_list, name='users_list'),
    path('overview/', views.overview, name='overview'),
    path('user/edit/<str:username>/', views.edit_user, name='edit_user'),
    path('user/delete/<str:username>/', views.delete_user, name='delete_user'),
    path('chat/', views.chatbot_response, name='chatbot_response'),
    path('login/', auth_views.LoginView.as_view(template_name='network/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('stage/add/', views.add_stage, name='add_stage'),
    path('stage/update/<int:stage_id>/', views.update_stage, name='update_stage'),
    path('stage/delete/<int:stage_id>/', views.delete_stage, name='delete_stage'),
    path('poste/add/', views.add_poste, name='add_poste'),
    path('poste/update/<int:poste_id>/', views.update_poste, name='update_poste'),
    path('poste/delete/<int:poste_id>/', views.delete_poste, name='delete_poste'),
    path('mobilite/add/', views.add_mobilite, name='add_mobilite'),
    path('mobilite/update/<int:mobilite_id>/', views.update_mobilite, name='update_mobilite'),
    path('mobilite/delete/<int:mobilite_id>/', views.delete_mobilite, name='delete_mobilite'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('domaines-utilisateurs/', views.domaines_utilisateurs, name='domaines_utilisateurs'),
   
    path('search/', views.search, name='search'),
    path('search_profiles/', views.search_profiles, name='search_profiles'),
    path('mentoring/', views.mentoring, name='mentoring'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social-Network-master/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
    
]

Social-Network-master/network/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class User(AbstractUser):
    profile_pic = models.ImageField(upload_to='profile_pic/', blank=True, null=True)
    bio = models.TextField(max_length=160, blank=True, null=True)
    cover = models.ImageField(upload_to='covers/', blank=True, null=True)
    user_group = models.CharField(max_length=10,blank=True, null=True)  # Alumni ou Eleve

    # Champs supplémentaires
    nationality = models.CharField(max_length=100, blank=True, null=True)
    promotion = models.CharField(max_length=10, blank=True, null=True)
    graduation_date = models.DateField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    
    # Majeurs, options, filières
    major = models.CharField(max_length=50, choices=[
        ('Aide à la Décision', 'Aide à la Décision'),
        ('Énergie', 'Énergie'),
        ('Matériau', 'Matériau'),
        ('Industrie', 'Industrie')
    ], blank=True, null=True)
    
    option = models.CharField(max_length=50, choices=[
        ('Génie Industriel', 'Génie Industriel'),
        ('Data Science et Digitalisation', 'Data Science et Digitalisation'),
        ('Énergie', 'Énergie')
    ], blank=True, null=True)
    
    filiere = models.CharField(max_length=100, choices=[
        ('Industrie 4.0', 'Industrie 4.0'),
        ('Ingénierie des Systèmes Complexes', 'Ingénierie des Systèmes Complexes'),
        ('Entreprendre en Afrique', 'Entreprendre en Afrique')
    ], blank=True, null=True)
    
    email = models.EmailField(blank=True, null=True)
    mentoring_1A = models.BooleanField(default=False)
    mentoring_2A = models.BooleanField(default=False)
    mentoring_3A = models.BooleanField(default=False)
    linkedin = models.URLField(blank=True, null=True)
    other_links = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.username

    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,
            'profile_pic': self.profile_pic.url if self.profile_pic else '',
            'first_name': self.first_name,
            'last_name': self.last_name,
            'user_group': self.user_group,
            'nationality': self.nationality,
            'promotion': self.promotion,
            'graduation_date': self.graduation_date,
            'phone_number': self.phone_number,
            'major': self.major,
            'option': self.option,
            'filiere': self.filiere,
            'email': self.email,
            'mentoring_1A': self.mentoring_1A,
            'mentoring_2A': self.mentoring_2A,
            'mentoring_3A': self.mentoring_3A,
            'linkedin': self.linkedin,
            'other_links': self.other_links,
            'electifs': [electif.serialize() for electif in self.electifs.all()],
        }

class Electif(models.Model):
    CONCEVOIR_RECHERCHER_MODULES = [
        ('Applications de la physique statistique aux SHS', 'Applications de la physique statistique aux SHS'),
        ('Introduction à la cyber Sécurité', 'Introduction à la cyber Sécurité'),
        ('Physique théorique', 'Physique théorique'),
        ('Gestion des risques', 'Gestion des risques'),
        ('Traitement d\'images et multimédias', 'Traitement d\'images et multimédias'),
        ('Processus Stochastiques', 'Processus Stochastiques'),
    ]
    
    DEVELOPPER_INNOVER_MODULES = [
        ('Logiciel industriel ABAQUS', 'Logiciel industriel ABAQUS'),
        ('Durabilité environnementale et justice sociale', 'Durabilité environnementale et justice sociale'),
        ('Réseaux Telecoms', 'Réseaux Telecoms'),
        ('La ville de demain : initiation à une démarche responsable et durable', 'La ville de demain : initiation à une démarche responsable et durable'),
        ('Nouvelles technologies pour la mobilité terrestre', 'Nouvelles technologies pour la mobilité terrestre'),
        ('Facteurs Humains', 'Facteurs Humains'),
    ]
    
    PRODUIRE_PROMOUVOIR_VENDRE_MODULES = [
        ('Marketing', 'Marketing'),
        ('Fondamentaux de la Finance du Marché', 'Fondamentaux de la Finance du Marché'),
        ('Finance d\'entreprise', 'Finance d\'entreprise'),
        ('Stratégie d\'entreprise', 'Stratégie d\'entreprise'),
        ('Entreprenariat social et défis socio-économiques en Afrique : stratégies pour un développement durable', 'Entreprenariat social et défis socio-économiques en Afrique : stratégies pour un développement durable'),
        ('Introduction à l\'analyse politique du monde contemporain', 'Introduction à l\'analyse politique du monde contemporain'),
    ]
    
    ELECTIF_TYPES = [
        ('concevoir_rechercher', 'Concevoir et Rechercher'),
        ('developper_innover', 'Développer et Innover'),
        ('produire_promouvoir_vendre', 'Produire, Promouvoir et Vendre')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='electifs')
    type = models.CharField(max_length=50, choices=ELECTIF_TYPES)
    competence = models.CharField(max_length=150)

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.type == 'concevoir_rechercher' and self.competence not in dict(self.CONCEVOIR_RECHERCHER_MODULES):
            raise ValidationError(f"{self.competence} n'est pas valide pour Convevoir et Rechercher")
        if self.type == 'developper_innover' and self.competence not in dict(self.DEVELOPPER_INNOVER_MODULES):
            raise ValidationError(f"{self.competence} n'est pas valide pour Développer et Innover")
        if self.type == 'produire_promouvoir_vendre' and self.competence not in dict(self.PRODUIRE_PROMOUVOIR_VENDRE_MODULES):
            raise ValidationError(f"{self.competence} n'est pas valide pour Produire, Promouvoir et Vendre")

    def __str__(self):
        return f"{self.get_type_display()} - {self.competence}"

    def serialize(self):
        return {
            'type': self.get_type_display(),
            'competence': self.competence,
        }

class Stage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stages', default=1)
    domaine = models.CharField(max_length=100, default='Inconnu')
    entreprise = models.CharField(max_length=100, default='Inconnu')
    theme = models.CharField(max_length=200, default='Inconnu')
    annee = models.PositiveIntegerField(default=2024)
    type_stage = models.CharField(max_length=50, choices=[
        ('PFE', 'PFE'),
        ('Cesure', 'Césure'),
        ('Operateur', 'Opérateur'),
        ('Academique', 'Académique')
    ], default='PFE')
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.domaine} - {self.entreprise}"

   
class Poste(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='postes', default=1)
    entreprise = models.CharField(max_length=100, default='Inconnu')
    domaine = models.CharField(max_length=100, default='Inconnu')
    poste_occupe = models.CharField(max_length=100, default='Inconnu')
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.domaine} - {self.entreprise}"

class Mobilite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mobilites', default=1)
    ecole = models.CharField(max_length=100, default='Inconnu')
    filiere = models.CharField(max_length=100, default='Inconnu')
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.ecole} - {self.filiere}"

class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

Social-Network-master/network/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import User, Electif

class ProfileForm(UserChangeForm):
    profile_pic = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'config-form-input'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'config-form-textarea'}), required=False)
    cover = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'config-form-input'}))
    nationality = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'config-form-input'}))
    promotion = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'config-form-input'}))
    graduation_date = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'config-form-input'}), required=False)
    phone_number = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'config-form-input'}))
    major = forms.ChoiceField(choices=User._meta.get_field('major').choices, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))
    option = forms.ChoiceField(choices=User._meta.get_field('option').choices, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))
    filiere = forms.ChoiceField(choices=User._meta.get_field('filiere').choices, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={'class': 'config-form-input'}))
    mentoring_1A = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'config-form-input'}))
    mentoring_2A = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'config-form-input'}))
    mentoring_3A = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'config-form-input'}))
    linkedin = forms.URLField(required=False, widget=forms.URLInput(attrs={'class': 'config-form-input'}))
    other_links = forms.URLField(required=False, widget=forms.URLInput(attrs={'class': 'config-form-input'}))
    
    competence_concevoir_rechercher = forms.ChoiceField(choices=Electif.CONCEVOIR_RECHERCHER_MODULES, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))
    competence_developper_innover = forms.ChoiceField(choices=Electif.DEVELOPPER_INNOVER_MODULES, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))
    competence_produire_promouvoir_vendre = forms.ChoiceField(choices=Electif.PRODUIRE_PROMOUVOIR_VENDRE_MODULES, required=False, widget=forms.Select(attrs={'class': 'config-form-select'}))

    class Meta:
        model = User
        fields = [
            'profile_pic', 'bio', 'cover', 'nationality', 'promotion', 'graduation_date', 'phone_number',
            'major', 'option', 'filiere', 'email', 'mentoring_1A', 'mentoring_2A', 'mentoring_3A',
            'linkedin', 'other_links', 'competence_concevoir_rechercher', 'competence_developper_innover',
            'competence_produire_promouvoir_vendre'
        ]

from django import forms
from django.contrib.auth.models import User

class EditUserForm(forms.ModelForm):
    USER_GROUP_CHOICES = [
        ('student', 'Student'),
        ('alumni', 'Alumni'),
        # Add other groups as needed
    ]
    
    user_group = forms.ChoiceField(choices=USER_GROUP_CHOICES, widget=forms.Select(attrs={'class': 'config-form-input'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'user_group', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'config-form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'config-form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'config-form-input'}),
            'email': forms.EmailInput(attrs={'class': 'config-form-input'}),
        }



from django import forms
from django.contrib.auth.models import User

class RegisterUserForm(forms.ModelForm):
    user_group = forms.ChoiceField(
        choices=[('Alumni', 'Alumni'), ('Eleve', 'Élève')],
        widget=forms.RadioSelect(attrs={'class': 'config-form-input'}),
        required=True
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'config-form-input'}), required=True)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'config-form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'config-form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'config-form-input'}),
            'email': forms.EmailInput(attrs={'class': 'config-form-input'}),
        }

Social-Network-master/network/templates/network/add_poste.html
{% extends "network/indexx.html" %}

{% block content %}
<div class="ajout">
  <h2>Ajouter un Poste</h2>
  <form method="post">
    {% csrf_token %}
    <label for="domaine">Domaine:</label>
    <input type="text" id="domaine" name="domaine">
    <label for="entreprise">Entreprise:</label>
    <input type="text" id="entreprise" name="entreprise">
    <button type="submit">Ajouter</button>
  </form>
</div>
{% endblock %}

Social-Network-master/network/templates/network/blog_content.html
{% extends "network/indexx.html" %}
{% block blog %}


<div id="blog-content">
    <h2>À propos de l'École Centrale Casablanca</h2>
    <section class="blog-section">
        <h3>Présentation</h3>
        <p>
            L'École Centrale Casablanca est un établissement prestigieux d'enseignement supérieur situé à Casablanca. 
            Elle offre des programmes de formation d'ingénieurs de haut niveau, visant à former des cadres dirigeants 
            pour les entreprises et l'industrie.
        </p>
    </section>
    <section class="blog-section">
        <h3>Environnement de Formation</h3>
        <p>
            Les étudiants de l'École Centrale Casablanca bénéficient d'un environnement de formation de qualité, 
            combinant à la fois des enseignements théoriques et pratiques, ainsi que des opportunités de recherche 
            et d'innovation.
        </p>
    </section>
    <section class="blog-section statistics">
        <h3>Quelques Chiffres</h3>
        <ul class="statistics-list">
            <li>500+ Étudiants</li>
            <li>30+ Partenariats Industriels</li>
            <li>20+ Programmes d'Échange</li>
            <li>95% Taux d'Emploi des Diplômés</li>
        </ul>
    </section>
    <section class="blog-section">
        <h3>Opportunités</h3>
        <p>
            Nous vous invitons à explorer les nombreuses opportunités qu'offre notre institution, que ce soit à 
            travers des stages, des projets de recherche ou des collaborations avec l'industrie.
        </p>
    </section>
</div>
{% endblock %}

Social-Network-master/network/templates/network/delete_stage.html
{% extends "network/indexx.html" %}

{% block content %}
<div class="ajout">
  <h2>Supprimer un Stage</h2>
  <p>Êtes-vous sûr de vouloir supprimer ce stage {{ stage.type_stage }} à {{ stage.entreprise }},domaine: {{ stage.domaine }}?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Supprimer</button>
    <a href="{% url 'profile' %}">Annuler</a>
  </form>
</div>
{% endblock %}

Social-Network-master/network/templates/network/full_profile.html
{% extends "network/indexx.html" %}

{% block content %}
<div class="full-div">
  <div class="tab-container">
    <button class="tab-button active" onclick="openTab(event, 'general')">Informations Générales</button>
    <button class="tab-button" onclick="openTab(event, 'electifs')">Électifs</button>
    <button class="tab-button" onclick="openTab(event, 'mobilites')">Mobilités</button>
    <button class="tab-button" onclick="openTab(event, 'stages')">Stages</button>
    <button class="tab-button" onclick="openTab(event, 'postes')">Postes</button>
    <button class="tab-button" onclick="openTab(event, 'majeurs')">Majeurs</button>
    <button class="tab-button" onclick="openTab(event, 'filieres')">Filières</button>
    <button class="tab-button" onclick="openTab(event, 'options')">Options</button>
  </div>

  <div id="general" class="tab-content active">
    <div class="full-profile-section">
      <h3>Informations Générales</h3>
      <p><strong>Nom d'utilisateur :</strong> {{ profile_user.username }}</p>
      <p><strong>Email :</strong> {{ profile_user.email }}</p>
      <p><strong>Nationalité :</strong> {{ profile_user.nationality }}</p>
      <p><strong>Promotion :</strong> {{ profile_user.promotion }}</p>
      <p><strong>Date de graduation :</strong> {{ profile_user.graduation_date }}</p>
      <p><strong>Numéro de téléphone :</strong> {{ profile_user.phone_number }}</p>
    
      <p><strong>LinkedIn :</strong> <a href="{{ profile_user.linkedin }}">{{ profile_user.linkedin }}</a></p>
      <p><strong>Autres liens :</strong> <a href="{{ profile_user.other_links }}">{{ profile_user.other_links }}</a></p>
    </div>
  </div>

  <div id="electifs" class="tab-content">
    <div class="full-profile-section">
      <h3>Électifs</h3>
      {% for electif in electifs %}
        <p><strong>{{ electif.get_type_display }} :</strong> {{ electif.competence }}</p>
      {% endfor %}
    </div>
  </div>

  <div id="mobilites" class="tab-content">
    <div class="full-profile-section">
      <h3>Mobilités</h3>
      {% for mobilite in mobilites %}
        <div class="full-mobilite-item">
          <p>{{ profile_user.first_name }} a effectué une mobilité à <strong>{{ mobilite.ecole }}</strong> dans la filière <strong>{{ mobilite.filiere }}</strong>.</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div id="stages" class="tab-content">
    <div class="full-profile-section">
      <h3>Stages</h3>
      {% for stage in stages %}
        <div class="full-stage-item">
          <p>{{ profile_user.first_name }} a réalisé un stage en <strong>{{ stage.domaine }}</strong> chez <strong>{{ stage.entreprise }}</strong> en <strong>{{ stage.annee }}</strong> sur le thème <em>{{ stage.theme }}</em>. Ce stage était un <strong>{{ stage.get_type_stage_display }}</strong>.</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div id="postes" class="tab-content">
    <div class="full-profile-section">
      <h3>Postes</h3>
      {% for poste in postes %}
        <div class="full-poste-item">
          <p>{{ profile_user.first_name }} a travaillé comme <strong>{{ poste.poste_occupe }}</strong> chez <strong>{{ poste.entreprise }}</strong> dans le domaine de <strong>{{ poste.domaine }}</strong>.</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div id="majeurs" class="tab-content">
    <div class="full-profile-section">
      <h3>Majeurs</h3>
      {% for majeur in majeurs %}
        <div class="full-majeur-item">
          <p>{{  profile_user.major }}</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div id="filieres" class="tab-content">
    <div class="full-profile-section">
      <h3>Filières</h3>
      {% for filiere in filieres %}
        <div class="full-filiere-item">
          <p>{{  profile_user.filiere}}</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div id="options" class="tab-content">
    <div class="full-profile-section">
      <h3>Options</h3>
      {% for option in options %}
        <div class="full-option-item">
          <p>{{  profile_user.option}}</p>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

Social-Network-master/network/templates/network/layout2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'network/styles2.css' %}" rel="stylesheet">
    <style>
        body {
            background-image: url("{% static 'network/Images/ECC.png' %}");
            background-size: cover;
            background-position: center;
        }
    </style>
</head>
<body>
<div class="center-box">
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</div>
</body>
</html>

Social-Network-master/network/templates/network/mentor.html
{% extends "network/indexx.html" %}

{% block content %}
<div class="mentor-container">
    <h1>Available Mentors</h1>
    <ul class="mentor-list-group">
        {% for mentor in mentors %}
        <li class="mentor-list-group-item d-flex justify-content-between align-items-center">
            <div class="mentor-details">
                {% if mentor.profile_pic %}
                <img src="{{ mentor.profile_pic.url }}" alt="{{ mentor.username }}" class="mentor-profile-pic">
                {% else %}
                <div class="mentor-icon">👤</div>
                {% endif %}
                {{ mentor.first_name }} {{ mentor.last_name }} ({{ mentor.user_group }})
            </div>
            <div class="mentor-circles">
                {% if mentor.mentoring_1A %}
                <span class="mentor-circle">1A</span>
                {% endif %}
                {% if mentor.mentoring_2A %}
                <span class="mentor-circle">2A</span>
                {% endif %}
                {% if mentor.mentoring_3A %}
                <span class="mentor-circle">3A</span>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

Social-Network-master/network/templates/network/postes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Domaines des utilisateurs</title>
</head>
<body>
    <h1>Domaines des postes et stages des utilisateurs</h1>
    
    <h2>Domaines :</h2>
    <ul>
        {% for domaine in domaines_utilisateurs %}
            <li>{{ domaine }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Social-Network-master/network/templates/network/profile.html
{% extends "network/indexx.html" %}
{% load static %}



{% block content %}
<h1>{{ profile_user.username }}</h1>
<div>
    <img src="{{ user_profile.profile_pic.url }}" alt="Profile Picture" />
</div>
<div>
    <p>Nom: {{ profile_user.username }} {{ profile_user.last_name }}</p>
    <p>Email: {{ profile_user.email }}</p>
    <p>Groupe: {{ profile_user.user_group }}</p>
    <p>Bio: {{ profile_user.bio }}</p>
</div>

<a href="{% url 'profile_view' %}" class="btn-login">Configurer le profil</a>

{% endblock %}

Social-Network-master/network/templates/network/temp.html
{% extends "network/layout2.html" %}

{% block title %}
    Sign Up | Network
{% endblock %}

{% block body %}

    <!-- <h2>Sign Up</h2> -->

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="custom-file mb-3">
            <input type="file" class="custom-file-input" id="customFile" name="filename">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

Social-Network-master/network/templates/network/update_poste.html
{% extends "network/indexx.html" %}

{% block content %}
<div class="ajout">
  <h2>Modifier un Poste</h2>
  <form method="post">
    {% csrf_token %}
    <label for="domaine">Domaine:</label>
    <input type="text" id="domaine" name="domaine" value="{{ poste.domaine }}"><br><br>
    <label for="entreprise">Entreprise:</label>
    <input type="text" id="entreprise" name="entreprise" value="{{ poste.entreprise }}"><br><br>
    <button type="submit">Mettre à jour</button>
  </form>
</div>
{% endblock %}